services:
  - type: web
    name: mind-matrix-api
    env: python
    rootDir: Backend
    buildCommand: "./build.sh"
    startCommand: "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: APP_NAME
        value: "Mind Matrix API"
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
